import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseBoolean, parseNumber, parseStringList } from './utils.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

const DEFAULT_EXTERNAL_WATCHLIST = [
  'ANET',
  'MRVL',
  'VRT',
  'ETN',
  'CEG',
  'VST',
  'AAON',
  'PWR',
  'FIX',
  'DELL',
  'HPE',
  'COHR',
  'LITE',
  'CIEN',
  'GLW',
  'ASML',
  'MSFT',
  'META',
  'ORCL',
  'CRM',
  'NOW',
  'SNOW',
  'MDB',
  'ADBE',
  'DDOG',
  'NET',
  'CRWV',
  'NBIS',
  'IREN',
  'WULF',
  'SOUN',
  'BBAI',
  'AI',
  'QQQ',
  'SMH',
];

export const STOCK_PROFILES = {
  NVDA: {
    name: 'NVIDIA Corporation',
    symbol: 'NVDA:NASDAQ',
    role: 'Core AI leader',
    aiCategory: 'ai_compute_leader',
    indmoneySlug: 'nvidia-corporation-share-price-nvda',
    thesisBucket: 'capex_taker',
    category: 'core',
    support: { holdAbove: 223, trimBelow: 220 },
    manualLevels: { holdAbove: 223, trimBelow: 220 },
    riskPenalty: 0,
    rotationTargetRank: 1,
  },
  MU: {
    name: 'Micron Technology Inc',
    symbol: 'MU:NASDAQ',
    role: 'Main profit engine / HBM memory winner',
    aiCategory: 'ai_memory_hbm',
    indmoneySlug: 'micron-technology-inc-share-price-mu',
    thesisBucket: 'capex_taker',
    category: 'profit_engine',
    support: { holdAbove: 1025, warnBelow: 1025, trimBelow: 1018 },
    manualLevels: { holdAbove: 1025, warnBelow: 1025, trimBelow: 1018 },
    riskPenalty: 0,
    rotationTargetRank: 3,
  },
  GOOGL: {
    name: 'Alphabet Inc Class A',
    symbol: 'GOOGL:NASDAQ',
    role: 'AI spender / laggard / loss stock',
    aiCategory: 'ai_cloud_hyperscaler',
    indmoneySlug: 'alphabet-inc-class-a-share-price-googl',
    thesisBucket: 'capex_spender',
    category: 'laggard',
    support: { holdAbove: 365, warnBelow: 365, partialExitBelow: 360, hardExitBelow: 350 },
    manualLevels: { holdAbove: 365, warnBelow: 365, partialExitBelow: 360, hardExitBelow: 350 },
    riskPenalty: -1,
    rotationSourceRank: 3,
  },
  AMD: {
    name: 'Advanced Micro Devices Inc',
    symbol: 'AMD:NASDAQ',
    role: 'Secondary AI chip exposure',
    aiCategory: 'ai_compute_leader',
    indmoneySlug: 'advanced-micro-devices-inc-share-price-amd',
    thesisBucket: 'capex_taker',
    category: 'secondary',
    support: { holdAbove: 501, warnBelow: 501, trimBelow: 498 },
    manualLevels: { holdAbove: 501, warnBelow: 501, trimBelow: 498 },
    riskPenalty: 0,
    rotationSourceRank: 4,
  },
  PLTR: {
    name: 'Palantir Technologies Inc',
    symbol: 'PLTR:NASDAQ',
    role: 'Speculative AI software / exit candidate if weak',
    aiCategory: 'ai_software_enterprise',
    indmoneySlug: 'palantir-technologies-inc-share-price-pltr',
    thesisBucket: 'software_spec',
    category: 'speculative',
    support: { holdAbove: 150, warnBelow: 150, hardExitBelow: 149 },
    manualLevels: { holdAbove: 150, warnBelow: 150, hardExitBelow: 149 },
    riskPenalty: -1,
    rotationSourceRank: 1,
  },
  SMCI: {
    name: 'Super Micro Computer Inc',
    symbol: 'SMCI:NASDAQ',
    role: 'High-beta AI server trade',
    aiCategory: 'ai_servers',
    indmoneySlug: 'super-micro-computer-inc-share-price-smci',
    thesisBucket: 'capex_taker',
    category: 'high_beta',
    support: { holdAbove: 48, warnBelow: 48, trimBelow: 47 },
    manualLevels: { holdAbove: 48, warnBelow: 48, trimBelow: 47 },
    riskPenalty: -1,
    rotationSourceRank: 5,
    rotationTargetRank: 5,
  },
  AVGO: {
    name: 'Broadcom Inc',
    symbol: 'AVGO:NASDAQ',
    role: 'AI networking / custom silicon winner',
    aiCategory: 'ai_custom_silicon_networking',
    indmoneySlug: 'broadcom-inc-share-price-avgo',
    thesisBucket: 'capex_taker',
    category: 'quality',
    support: { holdAbove: 475, warnBelow: 475, trimBelow: 470, optionalTrimNear: 490 },
    manualLevels: { holdAbove: 475, warnBelow: 475, trimBelow: 470, optionalTrimNear: 490 },
    riskPenalty: 0,
    rotationTargetRank: 2,
  },
  AMZN: {
    name: 'Amazon.com Inc',
    symbol: 'AMZN:NASDAQ',
    role: 'AI capex spender / rotation source if weak',
    aiCategory: 'ai_cloud_hyperscaler',
    indmoneySlug: 'amazoncom-inc-share-price-amzn',
    thesisBucket: 'capex_spender',
    category: 'laggard',
    support: { holdAbove: 255, warnBelow: 254, trimBelow: 254 },
    manualLevels: { holdAbove: 255, warnBelow: 254, trimBelow: 254 },
    riskPenalty: -1,
    rotationSourceRank: 2,
  },
  TSM: {
    name: 'Taiwan Semiconductor Manufacturing',
    symbol: 'TSM:NYSE',
    role: 'AI foundry stabilizer',
    aiCategory: 'ai_foundry_manufacturing',
    indmoneySlug: 'taiwan-semiconductor-manufacturing-share-price-tsm',
    thesisBucket: 'capex_taker',
    category: 'stabilizer',
    support: { holdAbove: 438, warnBelow: 436, trimBelow: 434 },
    manualLevels: { holdAbove: 438, warnBelow: 436, trimBelow: 434 },
    riskPenalty: 0,
    rotationTargetRank: 4,
  },
  ANET: {
    name: 'Arista Networks Inc',
    symbol: 'ANET:NYSE',
    role: 'External watchlist candidate',
    aiCategory: 'ai_custom_silicon_networking',
    indmoneySlug: 'marvell-technology-inc-share-price-mrvl',
    indmoneySlug: 'arista-networks-inc-share-price-anet',
    indmoneyFundamentals: {
      source: 'INDmoney seed',
      sourceDate: '2026-06-03',
      marketCap: 214_900_000_000,
      revenueTtm: 9_700_000_000,
      peTTM: 58.86,
      pegRatio: 2.195,
      epsTTM: 3.6294,
      netMargin: 38.32,
      operatingMargin: 42.71,
      returnOnEquity: 31.52,
      revenueGrowthTTMYoy: 28.59,
      quarterlyRevenueGrowthYoY: 35.18,
      analystTargetPrice: 188.2,
    },
    thesisBucket: 'capex_taker',
    category: 'quality',
    riskPenalty: 0,
    rotationTargetRank: 6,
  },
  MRVL: {
    name: 'Marvell Technology Inc',
    symbol: 'MRVL:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'ai_custom_silicon_networking',
    thesisBucket: 'capex_taker',
    category: 'secondary',
    riskPenalty: 0,
    rotationTargetRank: 7,
  },
  ARM: {
    name: 'Arm Holdings plc',
    symbol: 'ARM:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'other',
    thesisBucket: 'capex_taker',
    category: 'speculative',
    riskPenalty: -1,
    rotationTargetRank: 8,
  },
  ASML: {
    name: 'ASML Holding NV',
    symbol: 'ASML:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'ai_foundry_manufacturing',
    indmoneySlug: 'asml-holding-nv-share-price-asml',
    thesisBucket: 'capex_taker',
    category: 'quality',
    riskPenalty: 0,
    rotationTargetRank: 9,
  },
  MSFT: {
    name: 'Microsoft Corporation',
    symbol: 'MSFT:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'ai_cloud_hyperscaler',
    indmoneySlug: 'microsoft-corporation-share-price-msft',
    thesisBucket: 'capex_spender',
    category: 'quality',
    riskPenalty: 0,
  },
  META: {
    name: 'Meta Platforms Inc',
    symbol: 'META:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'ai_cloud_hyperscaler',
    indmoneySlug: 'meta-platforms-inc-share-price-meta',
    thesisBucket: 'capex_spender',
    category: 'quality',
    riskPenalty: 0,
  },
  ORCL: {
    name: 'Oracle Corporation',
    symbol: 'ORCL:NYSE',
    role: 'External watchlist candidate',
    aiCategory: 'ai_cloud_hyperscaler',
    indmoneySlug: 'oracle-corporation-share-price-orcl',
    thesisBucket: 'capex_spender',
    category: 'quality',
    riskPenalty: 0,
  },
  TSLA: {
    name: 'Tesla Inc',
    symbol: 'TSLA:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'other',
    thesisBucket: 'other',
    category: 'speculative',
    riskPenalty: -1,
  },
  IREN: {
    name: 'IREN Limited',
    symbol: 'IREN:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'speculative_ai_cloud_compute',
    indmoneySlug: 'iris-energy-limited-share-price-iren',
    thesisBucket: 'other',
    category: 'speculative',
    riskPenalty: -1,
  },
  CRWV: {
    name: 'CoreWeave Inc',
    symbol: 'CRWV:NASDAQ',
    role: 'External watchlist candidate',
    aiCategory: 'speculative_ai_cloud_compute',
    indmoneySlug: 'coreweave-inc-share-price-crwv',
    thesisBucket: 'capex_taker',
    category: 'speculative',
    riskPenalty: -1,
  },
  QQQ: {
    name: 'Invesco QQQ Trust',
    symbol: 'QQQ:NASDAQ',
    role: 'Benchmark',
    aiCategory: 'benchmark',
    thesisBucket: 'benchmark',
    category: 'benchmark',
    riskPenalty: 0,
  },
  SMH: {
    name: 'VanEck Semiconductor ETF',
    symbol: 'SMH:NYSEARCA',
    role: 'Benchmark',
    aiCategory: 'benchmark',
    thesisBucket: 'benchmark',
    category: 'benchmark',
    riskPenalty: 0,
  },
};

const EXTRA_AI_PROFILES = {
  VRT: ['Vertiv Holdings Co', 'VRT:NYSE', 'AI data center power/cooling candidate', 'ai_power_cooling_datacenter', 'quality', 'vertiv-holdings-co-share-price-vrt'],
  ETN: ['Eaton Corporation plc', 'ETN:NYSE', 'AI power infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'eaton-corporation-plc-share-price-etn'],
  CEG: ['Constellation Energy Corporation', 'CEG:NASDAQ', 'AI power infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'constellation-energy-corp-share-price-ceg'],
  VST: ['Vistra Corp', 'VST:NYSE', 'AI power infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'vst/vistra-corp-share-price'],
  AAON: ['AAON Inc', 'AAON:NASDAQ', 'AI cooling infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'aaon-inc-share-price-aaon'],
  PWR: ['Quanta Services Inc', 'PWR:NYSE', 'Grid infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'quanta-services-inc-share-price-pwr'],
  FIX: ['Comfort Systems USA Inc', 'FIX:NYSE', 'Data center infrastructure candidate', 'ai_power_cooling_datacenter', 'quality', 'comfort-systems-usa-inc-share-price-fix'],
  DELL: ['Dell Technologies Inc', 'DELL:NYSE', 'AI server candidate', 'ai_servers', 'secondary', 'dell-technologies-inc-class-c-shares-share-price-dell'],
  HPE: ['Hewlett Packard Enterprise Co', 'HPE:NYSE', 'AI server candidate', 'ai_servers', 'secondary', 'hewlett-packard-enterprise-co-share-price-hpe'],
  COHR: ['Coherent Corp', 'COHR:NYSE', 'AI optical/connectivity candidate', 'ai_optical_connectivity', 'secondary', 'coherent-corp-share-price-cohr'],
  LITE: ['Lumentum Holdings Inc', 'LITE:NASDAQ', 'AI optical/connectivity candidate', 'ai_optical_connectivity', 'secondary', 'lumentum-holdings-inc-share-price-lite'],
  CIEN: ['Ciena Corporation', 'CIEN:NYSE', 'AI optical/connectivity candidate', 'ai_optical_connectivity', 'secondary', 'ciena-corporation-share-price-cien'],
  GLW: ['Corning Incorporated', 'GLW:NYSE', 'AI connectivity candidate', 'ai_optical_connectivity', 'quality', 'corning-inc-share-price-glw'],
  CRM: ['Salesforce Inc', 'CRM:NYSE', 'Enterprise AI software candidate', 'ai_software_enterprise', 'quality', 'salesforce-inc-share-price-crm'],
  NOW: ['ServiceNow Inc', 'NOW:NYSE', 'Enterprise AI software candidate', 'ai_software_enterprise', 'quality', 'servicenow-inc-share-price-now'],
  SNOW: ['Snowflake Inc', 'SNOW:NYSE', 'Enterprise AI software candidate', 'ai_software_enterprise', 'secondary', 'snowflake-inc-share-price-snow'],
  MDB: ['MongoDB Inc', 'MDB:NASDAQ', 'Enterprise AI software candidate', 'ai_software_enterprise', 'secondary', 'mongodb-inc-share-price-mdb'],
  ADBE: ['Adobe Inc', 'ADBE:NASDAQ', 'Enterprise AI software candidate', 'ai_software_enterprise', 'quality', 'adobe-systems-inc-share-price-adbe'],
  DDOG: ['Datadog Inc', 'DDOG:NASDAQ', 'Enterprise AI software candidate', 'ai_software_enterprise', 'secondary', 'datadog-inc-share-price-ddog'],
  NET: ['Cloudflare Inc', 'NET:NYSE', 'Enterprise AI software candidate', 'ai_software_enterprise', 'secondary', 'cloudflare-inc-share-price-net'],
  NBIS: ['Nebius Group NV', 'NBIS:NASDAQ', 'Speculative AI cloud candidate', 'speculative_ai_cloud_compute', 'speculative', 'nebius-group-nv-share-price-nbis'],
  WULF: ['TeraWulf Inc', 'WULF:NASDAQ', 'Speculative AI compute candidate', 'speculative_ai_cloud_compute', 'speculative', 'terawulf-inc-share-price-wulf'],
  SOUN: ['SoundHound AI Inc', 'SOUN:NASDAQ', 'Speculative AI software candidate', 'speculative_ai_cloud_compute', 'speculative', 'soundhound-ai-inc-share-price-soun'],
  BBAI: ['BigBear.ai Holdings Inc', 'BBAI:NYSE', 'Speculative AI software candidate', 'speculative_ai_cloud_compute', 'speculative', 'bigbearai-holdings-inc-share-price-bbai'],
  AI: ['C3.ai Inc', 'AI:NYSE', 'Speculative AI software candidate', 'speculative_ai_cloud_compute', 'speculative', 'c3ai-inc-share-price-ai'],
};

for (const [ticker, [name, symbol, role, aiCategory, category, indmoneySlug]] of Object.entries(EXTRA_AI_PROFILES)) {
  STOCK_PROFILES[ticker] = {
    name,
    symbol,
    role,
    aiCategory,
    indmoneySlug,
    thesisBucket: ['ai_cloud_hyperscaler', 'ai_software_enterprise'].includes(aiCategory) ? 'capex_spender' : 'capex_taker',
    category,
    riskPenalty: category === 'speculative' ? -1 : 0,
  };
}

const INDMONEY_FUNDAMENTAL_SEEDS = {
  NVDA: {
    indmoneySlug: 'nvidia-corporation-share-price-nvda',
    indmoneyFundamentals: {
      source: 'INDmoney seed',
      sourceDate: '2026-06-03',
      marketCap: 5_400_000_000_000,
      revenueTtm: 253_500_000_000,
      peTTM: 34.36,
      pegRatio: 0.6913,
      epsTTM: 4.696,
      netMargin: 62.97,
      operatingMargin: 65.6,
      returnOnEquity: 114.29,
      quarterlyRevenueGrowthYoY: 85.23,
      revenueGrowthTTMYoy: 85.23,
    },
  },
  MRVL: {
    indmoneySlug: 'marvell-technology-group-ltd-share-price-mrvl',
    indmoneyFundamentals: {
      source: 'INDmoney seed',
      sourceDate: '2026-06-03',
      marketCap: 192_100_000_000,
      revenueTtm: 8_700_000_000,
      peTTM: 75.15,
      pegRatio: 1.2401,
      epsTTM: 2.8289,
      netMargin: 28.99,
      operatingMargin: 14.48,
      returnOnEquity: 16.03,
      revenueGrowthTTMYoy: 42.26,
      quarterlyRevenueGrowthYoY: 27.55,
      analystTargetPrice: 222.55,
    },
  },
  AVGO: {
    indmoneySlug: 'broadcom-inc-share-price-avgo',
    indmoneyFundamentals: {
      source: 'INDmoney seed',
      sourceDate: '2026-06-03',
      marketCap: 2_100_000_000_000,
      revenueTtm: 68_300_000_000,
      peTTM: 86.92,
      pegRatio: 0.9719,
      epsTTM: 11.3609,
      netMargin: 36.57,
      operatingMargin: 44.95,
      returnOnEquity: 33.37,
      quarterlyRevenueGrowthYoY: 29.46,
      revenueGrowthTTMYoy: 29.46,
    },
  },
  VRT: {
    indmoneySlug: 'vertiv-holdings-co-share-price-vrt',
    indmoneyFundamentals: {
      source: 'INDmoney seed',
      sourceDate: '2026-06-03',
      marketCap: 124_200_000_000,
      revenueTtm: 10_800_000_000,
      peTTM: 81.25,
      pegRatio: 1.6212,
      epsTTM: 6.4894,
      netMargin: 14.37,
      operatingMargin: 16.61,
      returnOnEquity: 45.1,
      revenueGrowthTTMYoy: 27.69,
      quarterlyRevenueGrowthYoY: 30.11,
    },
  },
};

for (const [ticker, seed] of Object.entries(INDMONEY_FUNDAMENTAL_SEEDS)) {
  if (STOCK_PROFILES[ticker]) {
    STOCK_PROFILES[ticker] = {
      ...STOCK_PROFILES[ticker],
      ...seed,
      indmoneyFundamentals: {
        ...(STOCK_PROFILES[ticker].indmoneyFundamentals || {}),
        ...(seed.indmoneyFundamentals || {}),
      },
    };
  }
}

export function buildPortfolioAlertConfig(env = process.env) {
  const portfolioPath = env.PORTFOLIO_JSON_PATH || path.join(PROJECT_ROOT, 'data', 'portfolio.json');

  return {
    projectRoot: PROJECT_ROOT,
    enabled: parseBoolean(env.PORTFOLIO_ALERTS_ENABLED, false),
    dryRun: parseBoolean(env.PORTFOLIO_ALERTS_DRY_RUN, true),
    pollingIntervalMsPreMarket: Math.max(
      5_000,
      parseNumber(
        env.PORTFOLIO_ALERTS_POLL_SECONDS_PRE_MARKET,
        parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS, 5),
      ) * 1000,
    ),
    pollingIntervalMsRegular: Math.max(
      5_000,
      parseNumber(
        env.PORTFOLIO_ALERTS_POLL_SECONDS_REGULAR,
        parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS, 5),
      ) * 1000,
    ),
    pollingIntervalMsPostMarket: Math.max(
      5_000,
      parseNumber(
        env.PORTFOLIO_ALERTS_POLL_SECONDS_POST_MARKET,
        parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS, 5),
      ) * 1000,
    ),
    pollingIntervalMsClosed: Math.max(
      5_000,
      parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS_CLOSED, parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS, 5)) * 1000,
    ),
    pollingIntervalMs: Math.max(5_000, parseNumber(env.PORTFOLIO_ALERTS_POLL_SECONDS, 5) * 1000),
    dailySummaryTimeEt: env.PORTFOLIO_ALERTS_DAILY_SUMMARY_ET || '17:15',
    userTimezone: env.PORTFOLIO_ALERT_USER_TIMEZONE || 'Asia/Kolkata',
    marketTimezone: 'America/New_York',
    portfolioPath,
    portfolioUrl: env.PORTFOLIO_JSON_URL || '',
    researchCachePath:
      env.PORTFOLIO_ALERT_RESEARCH_CACHE_PATH || path.join(PROJECT_ROOT, 'data', 'ai-signals.json'),
    indMoneyCachePath:
      env.PORTFOLIO_ALERT_INDMONEY_CACHE_PATH || path.join(PROJECT_ROOT, 'data', 'indmoney-fundamentals.json'),
    statePath: env.PORTFOLIO_ALERT_STATE_PATH || path.join(PROJECT_ROOT, 'data', 'portfolio-alert-state.json'),
    eventsPath: env.PORTFOLIO_ALERT_EVENTS_PATH || path.join(PROJECT_ROOT, 'data', 'portfolio-alert-events.json'),
    whatsapp: {
      recipient: env.PORTFOLIO_ALERT_RECIPIENT || '',
      agentUrl: env.WHATSAPP_AGENT_URL || 'http://127.0.0.1:3001/send',
      agentSecret: env.WHATSAPP_AGENT_SECRET || '',
      threadReplies: parseBoolean(env.PORTFOLIO_ALERT_THREAD_REPLIES, true),
    },
    thresholds: {
      targetInrNetProfit: parseNumber(env.PORTFOLIO_ALERT_TARGET_INR, 500000),
      taxRate: parseNumber(env.PORTFOLIO_ALERT_TAX_RATE, 0.3),
      usdInrRate: parseNumber(env.PORTFOLIO_ALERT_USD_INR, 86),
      dailyAlertCap: Math.max(1, Math.round(parseNumber(env.PORTFOLIO_ALERT_DAILY_CAP, 12))),
      staleRegularMinutes: parseNumber(env.PORTFOLIO_ALERT_STALE_REGULAR_MINUTES, 15),
      staleExtendedMinutes: parseNumber(env.PORTFOLIO_ALERT_STALE_EXTENDED_MINUTES, 90),
      portfolioSnapshotFreshnessMinutes: parseNumber(env.PORTFOLIO_ALERT_PORTFOLIO_FRESHNESS_MINUTES, 360),
      portfolioReconciliationToleranceUsd: parseNumber(env.PORTFOLIO_ALERT_RECONCILIATION_TOLERANCE_USD, 2),
      sameTriggerCooldownMinutes: parseNumber(env.PORTFOLIO_ALERT_SAME_TRIGGER_COOLDOWN_MINUTES, 30),
      l1CooldownMinutes: parseNumber(env.PORTFOLIO_ALERT_L1_COOLDOWN_MINUTES, 60),
      l2MaxPerSession: Math.max(1, Math.round(parseNumber(env.PORTFOLIO_ALERT_L2_MAX_PER_SESSION, 2))),
      watchConfirmationMinutes: parseNumber(env.PORTFOLIO_ALERT_WATCH_CONFIRM_MINUTES, 5),
      actionConfirmationMinutes: parseNumber(env.PORTFOLIO_ALERT_ACTION_CONFIRM_MINUTES, 15),
      preMarketEnabled: parseBoolean(env.PORTFOLIO_ALERT_PREMARKET_ENABLED, true),
      postMarketEnabled: parseBoolean(env.PORTFOLIO_ALERT_POSTMARKET_ENABLED, true),
      rotationEnabled: parseBoolean(env.PORTFOLIO_ALERT_ROTATION_ENABLED, true),
      newsScoringEnabled: parseBoolean(env.PORTFOLIO_ALERT_NEWS_ENABLED, true),
      earningsEnabled: parseBoolean(env.PORTFOLIO_ALERT_EARNINGS_ENABLED, true),
      buyPowerFloorUsd: parseNumber(env.PORTFOLIO_ALERT_BUYING_POWER_FLOOR_USD, 25),
      targetHorizonDays: parseNumber(env.PORTFOLIO_ALERT_TARGET_HORIZON_DAYS, 60),
      maxAcceptableDrawdownPct: parseNumber(env.PORTFOLIO_ALERT_MAX_DRAWDOWN_PCT, 8),
      riskTolerance: env.PORTFOLIO_ALERT_RISK_TOLERANCE || 'moderate',
      maxDailyDeploymentPct: parseNumber(env.PORTFOLIO_ALERT_MAX_DAILY_DEPLOYMENT_PCT, 0.25),
      opportunityRiskOffThreshold: parseNumber(env.PORTFOLIO_ALERT_OPPORTUNITY_RISK_OFF, 85),
      opportunityNeutralThreshold: parseNumber(env.PORTFOLIO_ALERT_OPPORTUNITY_NEUTRAL, 75),
      opportunityRiskOnThreshold: parseNumber(env.PORTFOLIO_ALERT_OPPORTUNITY_RISK_ON, 65),
      cashReserveRiskOffPct: parseNumber(env.PORTFOLIO_ALERT_CASH_RESERVE_RISK_OFF, 0.5),
      cashReserveNeutralPct: parseNumber(env.PORTFOLIO_ALERT_CASH_RESERVE_NEUTRAL, 0.3),
      cashReserveRiskOnPct: parseNumber(env.PORTFOLIO_ALERT_CASH_RESERVE_RISK_ON, 0.2),
    },
    providers: {
      price: env.PORTFOLIO_ALERT_PRICE_PROVIDER || 'google_finance',
      news: env.PORTFOLIO_ALERT_NEWS_PROVIDER || 'google_news',
      earnings: env.PORTFOLIO_ALERT_EARNINGS_PROVIDER || 'finnhub_optional',
      indmoneyMcpEnabled: parseBoolean(env.INDMONEY_MCP_ENABLED, true),
      indmoneyMcpSourcePriority: env.INDMONEY_MCP_SOURCE_PRIORITY || 'mcp_first',
      indmoneyMcpCacheSeconds: parseNumber(env.INDMONEY_MCP_CACHE_SECONDS, 30),
      indmoneyMcpAllowLegacyFallback: parseBoolean(env.PORTFOLIO_ALERT_INDMONEY_MCP_LEGACY_FALLBACK, false),
      indmoneyFundamentals: parseBoolean(env.PORTFOLIO_ALERT_INDMONEY_FUNDAMENTALS, true),
      indmoneyTimeoutMs: parseNumber(env.PORTFOLIO_ALERT_INDMONEY_TIMEOUT_MS, 5000),
      indmoneyRefreshHourEt: parseNumber(env.PORTFOLIO_ALERT_INDMONEY_REFRESH_HOUR_ET, 8),
      finnhubApiKey: env.FINNHUB_API_KEY || '',
    },
    watchlist: {
      external: parseStringList(env.PORTFOLIO_ALERT_WATCHLIST_TICKERS, DEFAULT_EXTERNAL_WATCHLIST),
    },
    stockProfiles: STOCK_PROFILES,
    userAgent:
      env.USER_AGENT ||
      'Mozilla/5.0 (compatible; MarketDashboardAlerts/1.0; +https://markets.healthymealspot.com)',
  };
}
